const menudata = [
  {
    id: 1,
    category: "lunch",
    img: "https://vismaifood.com/storage/app/uploads/public/e12/7b7/127/thumb__700_0_0_0_auto.jpg",
    title: "dum biryani",
    price: 350,
    des: "An authentic Mughlai dish, Biryani is an aromatic delicacy loved by all. ",
  },
  {
    id: 2,
    category: "lunch",
    img: "https://www.allrecipes.com/thmb/1ul-jdOz8H4b6BDrRcYOuNmJgt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/239867chef-johns-chicken-tikka-masala-ddmfs-3X4-0572-e02a25f8c7b745459a9106e9eb13de10.jpg",
    title: "Chicken Tikka Masala",
    price: 400,
    des: "The world-famous sauce used in tikka masala is mainly tomato-based, with some richness added by cream or thick yogurt.",
  },
  {
    id: 3,
    category: "breakfast",
    img: "https://cdn2.foodviva.com/static-content/food-images/healthy-recipes/oats-upma-recipe/oats-upma-recipe.jpg",
    title: "oats upma",
    price: 70,
    des: "oats are actually the grains of the grass known as Avena sativa. ",
  },
  {
    id: 4,
    category: "lunch",
    img: "https://www.connoisseurusveg.com/wp-content/uploads/2023/04/chana-masala-sq.jpg",
    title: "CHANA MASALA",
    price: 200,
    des: "Chana Masala, also known as chole masala, or chholay.",
  },
  {
    id: 5,
    category: "snacks",
    img: "https://i.ytimg.com/vi/r4PzQrEaAE8/maxresdefault.jpg",
    title: "Bread Vada",
    price: 60,
    des: "bread, baked food product made of flour or meal that is moistened, kneaded, and sometimes fermented.",
  },
  {
    id: 6,
    category: "snacks",
    img: "https://4.bp.blogspot.com/-MsiRfVL5OSI/WxYvVUbWY7I/AAAAAAAADYI/AqA-sNemf4sl40OejVZrRbe_A62LZkQgQCLcBGAs/s1600/Poha%2BPotatoes%2BCheese%2BCroquettes%2BRecipe%2B-%2BPriya%2BR%2B-%2BMagic%2Bof%2BIndian%2BRasoi%2B%25288%2529.JPG",
    title: "Poha Croquettes",
    price: 60,
    des: "Poha is flattened rice that is steam cooked with onions, spices and herbs. The word “poha” refers to the flattened rice itself and as well the dish made with it.",
  },
  {
    id: 7,
    category: "breakfast",
    img: "https://media-cdn.tripadvisor.com/media/photo-s/12/ac/df/f0/chole-bhature.jpg",
    title: "Chole Bhature",
    price: 70,
    des: "Chole Bhature is a food dish popular in the Northern areas",
  },
  {
    id: 8,
    category: "lunch",
    img: "https://www.whiskaffair.com/wp-content/uploads/2016/09/Palak-Rice-2-3.jpg",
    title: "Palak rice",
    price: 250,
    des: "Paneer is a creamy Indian cheese that’s made from curdled milk and some sort of fruit or vegetable acid like lemon juice.",
  },
  {
    id: 9,
    category: "snacks",
    img: "https://cdn.shopaccino.com/refresh/articles/sprout-salad-418870_l.jpg",
    title: "Salad Recipe",
    price: 200,
    des: "raw greens (such as lettuce) often combined with other vegetables and toppings and served especially with dressing.",
  },
  {
    id: 10,
    category: "breakfast",
    img: "https://static.toiimg.com/thumb/84229474.cms?width=1200&height=900",
    title: "Multigrain Roti",
    price: 150,
    des: "made with the combination of whole wheat flour ",
  },
];
export default menudata;
